### ISSUE TITLE
eslint / Definition for rule '@typescript-eslint/no-unused-expressions' was not found.

### ISSUE THREAD

**Issue by aheissenberger** [vikejs/bati#354]
**Describe the bug**
The generation of a template will fail with this disabled rule:
`// eslint-disable-next-line @typescript-eslint/no-unused-expressions`

```
 ERROR  [eslint] Error while parsing or fixing file layouts/LayoutDefault.tsx:                                                                                                                                                                                   8:36:43 AM
layouts/LayoutDefault.tsx:9:1 => Definition for rule '@typescript-eslint/no-unused-expressions' was not found.

  layouts/LayoutDefault.tsx:9:1 => Definition for rule '@typescript-eslint/no-unused-expressions' was not found.
  at oSr (packages/core/dist/index.js:962:2356)
  at $Ur (packages/core/dist/index.js:965:774)
  at xns (packages/core/dist/index.js:974:2105)
  at executeOperationFile (packages/cli/dist/index.js:60:24)
  at async main (packages/cli/dist/index.js:296:16)
  at async Object.run (packages/cli/dist/index.js:2050:7)
  at async runCommand (packages/cli/dist/index.js:639:16)
  at async runMain (packages/cli/dist/index.js:766:7)
  at async run (packages/cli/dist/index.js:2066:3) 
```

**To Reproduce**
add this to `boilerplates/react/files/layouts/LayoutDefault.tsx`:
```tsx
// eslint-disable-next-line @typescript-eslint/no-unused-expressions
import.meta.env.PROD && console.log("PROD Mode")

export default function LayoutDefault({ children }: { children: React.ReactNode }) {
  return (
```

run this command line:
`pnpm cli --react`

**Expected behavior**

no eslint error, no error when generating the template

**Additional context**

**Comment by magne4000** [comment]
Fixed by https://github.com/vikejs/bati/commit/0c037118c8eb46943662ff45d87d7bfbc464eca3
